name: Release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [arm, arm64, amd64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Release
      uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.20"
        project_path: "./cmd/thangmo-job"
        binary_name: "thangmo-job"
